export const SIGNUP_USER_REQ = "SIGNUP_USER_REQ"
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS"
export const SIGNUP_USER_FAIL = "SIGNUP_USER_FAIL"

export const LOGIN_USER_REQ = "LOGIN_USER_REQ"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL"