export const SIGNUP_USER_REQ = "SIGNUP_USER_REQ"
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS"
export const SIGNUP_USER_FAIL = "SIGNUP_USER_FAIL"

export const LOGIN_USER_REQ = "LOGIN_USER_REQ"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL"


export const LOAD_USER_REQ = "LOAD_USER_REQ"
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS"
export const LOAD_USER_FAIL = "LOAD_USER_FAIL"