import Head from "next/head";
import Add from "../components/Detail/Add";

export default function () {
  return (
    <>
      <Head>
        <title>Shadamon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Add />
    </>
  );
}
