import Head from "next/head";
import MainAdmin from "../components/admin/Main/Main";
import SideMenu from "../components/admin/Menu/Menu";

export default function Admin() {

  return (
    <>
      <Head>
        <title>admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <MainAdmin/>
    </>
  );
}
