import Head from "next/head";
import BiggestPost from "../components/Home/BiggestAd";
import CategoryLocation from "../components/Home/CategoryLocation";
import Heading from "../components/Home/Heading";

export default function Home() {
  return (
    <>
      <Head>
        <title>Shadamon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading />
      <main className="h-[100vh] bg-body-bg">
        <div className="flex items-center justify-center">
          <div className="border w-[250px]">Category Area</div>
          <div className="border w-[515px]">
            <CategoryLocation />
            <BiggestPost />
          </div>
          <div className="border w-[210px]">Advertisement</div>
        </div>
      </main>
    </>
  );
}
