export const GET_PARENT_CATEGORY = "GET_PARENT_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_FEATURES = "GET_FEATURES";
export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY";
export const GET_LOCATIONS = "GET_LOCATIONS";
export const GET_SUB_CATEGORIES = "GET_SUB_CATEGORIES";
export const GET_CATEGORIES_UNDER_PARENT = "GET_CATEGORIES_UNDER_PARENT";
export const GET_FEATURE_UNDER_SUB = "GET_FEATURE_UNDER_SUB";

