export const GET_PARENT_CATEGORY = "GET_PARENT_CATEGORY";
export const CREATE_CATEGORY_REQ = "CREATE_CATEGORY_REQ";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const GET_CATEGORIES_REQ = "GET_CATEGORIES_REQ";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_FEATURES = "GET_FEATURES";
export const CREATE_SUBCATEGORY_REQ = "CREATE_SUBCATEGORY_REQ";
export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY";
export const GET_LOCATIONS = "GET_LOCATIONS";
export const GET_SUB_CATEGORIES = "GET_SUB_CATEGORIES";
export const GET_CATEGORIES_UNDER_PARENT = "GET_CATEGORIES_UNDER_PARENT";
export const GET_FEATURE_UNDER_SUB = "GET_FEATURE_UNDER_SUB";

export const GET_ALL_BUTTONS = "GET_ALL_BUTTONS" 
export const DELETE_CATEGORY_REQ = "DELETE_CATEGORY_REQ" 
export const DELETE_CATEGORY = "DELETE_CATEGORY" 
export const EDIT_CATEGORY_REQ = "EDIT_CATEGORY_REQ" 
export const EDIT_CATEGORY = "EDIT_CATEGORY" 

export const DELETE_SUB_CATEGORY_REQ = "DELETE_SUB_CATEGORY_REQ" 
export const DELETE_SUB_CATEGORY = "DELETE_SUB_CATEGORY" 
export const EDIT_SUB_CATEGORY_REQ = "EDIT_SUB_CATEGORY_REQ" 
export const EDIT_SUB_CATEGORY = "EDIT_SUB_CATEGORY" 

export const CREATE_FEATURE_REQ = "CREATE_FEATURE_REQ"
export const CREATE_FEATURE = "CREATE_FEATURE"
export const EDIT_FEATURE_REQ = "EDIT_FEATURE_REQ"
export const EDIT_FEATURE = "EDIT_FEATURE"
export const DELETE_FEATURE_REQ = "DELETE_FEATURE_REQ"
export const DELETE_FEATURE = "DELETE_FEATURE"

export const GET_PARENT_CAT_SUB = "GET_PARENT_CAT_SUB"

