export const GET_PARENT_CATEGORY = "GET_PARENT_CATEGORY";
export const CREATE_CATEGORY_REQ = "CREATE_CATEGORY_REQ";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_FEATURES = "GET_FEATURES";
export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY";
export const GET_LOCATIONS = "GET_LOCATIONS";
export const GET_SUB_CATEGORIES = "GET_SUB_CATEGORIES";
export const GET_CATEGORIES_UNDER_PARENT = "GET_CATEGORIES_UNDER_PARENT";
export const GET_FEATURE_UNDER_SUB = "GET_FEATURE_UNDER_SUB";

export const GET_ALL_BUTTONS = "GET_ALL_BUTTONS" 
export const DELETE_CATEGORY_REQ = "DELETE_CATEGORY_REQ" 
export const DELETE_CATEGORY = "DELETE_CATEGORY" 
export const EDIT_CATEGORY_REQ = "EDIT_CATEGORY_REQ" 
export const EDIT_CATEGORY = "EDIT_CATEGORY" 

