export const CREATE_PACKAGE_REQ = "CREATE_PACKAGE_REQ"; 
export const CREATE_PACKAGE = "CREATE_PACKAGE"; 

export const EDIT_PACKAGE_REQ = "EDIT_PACKAGE_REQ"; 
export const EDIT_PACKAGE = "EDIT_PACKAGE"; 

export const DELETE_PACKAGE_REQ = "DELETE_PACKAGE_REQ"; 
export const DELETE_PACKAGE = "DELETE_PACKAGE"; 

export const GET_ALL_PACKAGE = "GET_ALL_PACKAGE"