export const CREATE_PACKAGE_REQ = "CREATE_PACKAGE_REQ"; 
export const CREATE_PACKAGE = "CREATE_PACKAGE"; 

export const EDIT_PACKAGE_REQ = "EDIT_PACKAGE_REQ"; 
export const EDIT_PACKAGE = "EDIT_PACKAGE"; 

export const DELETE_PACKAGE_REQ = "DELETE_PACKAGE_REQ"; 
export const DELETE_PACKAGE = "DELETE_PACKAGE"; 

export const GET_ALL_PACKAGE = "GET_ALL_PACKAGE"


export const GET_ALL_SUBCATEGORIES = "GET_ALL_SUBCATEGORIES" 
export const GET_ALL_SORTS = "GET_ALL_SORTS" 

export const CREATE_COUPON_REQ = "CREATE_COUPON_REQ"; 
export const CREATE_COUPON = "CREATE_COUPON"; 


export const ADD_VAT_REQ = "ADD_VAT_REQ"; 
export const ADD_VAT = "ADD_VAT"; 

