export const CREATE_PRODUCT_REQ = "CREATE_PRODUCT_REQ"
export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const GET_ALL_PRODUCT= "GET_ALL_PRODUCT"

export const EDIT_PRODUCT_REQ = "EDIT_PRODUCT_REQ"
export const EDIT_PRODUCT = "EDIT_PRODUCT"

export const DELETE_PRODUCT_REQ = "DELETE_PRODUCT_REQ"
export const DELETE_PRODUCT = "DELETE_PRODUCT"