export const CREATE_PRODUCT_REQ = "CREATE_PRODUCT_REQ"
export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const GET_ALL_PRODUCT= "GET_ALL_PRODUCT"

export const EDIT_PRODUCT_REQ = "EDIT_PRODUCT_REQ"
export const EDIT_PRODUCT = "EDIT_PRODUCT"

export const DELETE_PRODUCT_REQ = "DELETE_PRODUCT_REQ"
export const DELETE_PRODUCT = "DELETE_PRODUCT"

export const DELETE_PRODUCT_IMG_REQ = "DELETE_PRODUCT_IMG_REQ"
export const DELETE_PRODUCT_IMG = "DELETE_PRODUCT_IMG"

export const APPROVE_PD_IMG_REQ = "APPROVE_PD_IMG_REQ" 
export const APPROVE_PD_IMG = "APPROVE_PD_IMG" 