import Head from "next/head";
import AdminModal from "../../components/admin/AllModal/AdminModal";
import BlogBtn from "../../components/admin/blogsPage/BlogBtn";
import CatTable from "../../components/admin/blogsPage/CatTable";
import TopAvatarArea from "../../components/admin/blogsPage/TopAvatarArea";
import SideMenu from "../../components/admin/Menu/Menu";
import { ToastContainer } from "react-toastify";

import "react-toastify/dist/ReactToastify.css";
import SmallModal from "../../components/admin/AllModal/SmallModal";
import SettingBtnArea from "../../components/admin/SettingsPage/SettingBtnArea";
import { Divider } from "antd";
import LocationTable from "../../components/admin/SettingsPage/LocationTable";

export default function Admin() {
  return (
    <>
      <Head>
        <title>Settings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer/>
      <div className="flex gap-1">
        <div className="min-h-screen bg-[#001529]">
          <SideMenu activeItem="6" />
        </div>
        <AdminModal />
        <SmallModal/>
        <div className="mr-4 w-full">
          <TopAvatarArea/>
          <SettingBtnArea/>
          <Divider className="my-1"/>
          <LocationTable/>
        </div>
      </div>
    </>
  );
}
